<?php
$_sellerInfomation=$block->getSellerInfomation();
?>
<div class="block block-maketplace-profile">
	<div class="page-title">
		<h2><?php /* @escapeNotVerified */ echo __('Edit Profile infomation') ?></h2>
	</div>
	<div class="block-content">
		<form class="form form-edit-profile-seller" method="post" enctype="multipart/form-data" action="<?php /* @escapeNotVerified */ echo $block->getUrl('marketplace/seller/editPost') ?>" >
			<input type="hidden" name="sellerId" value="<?php echo $_sellerInfomation['id'] ?>" />
			<?php echo $block->getBlockHtml('formkey')?>
			<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Profile Information') ?></span></legend>
			<div class="field twitterid">
				<label class="label" for="twitterid"><span><?php /* @escapeNotVerified */ echo __('Twitter ID') ?></span></label>				
				<div class="control">
					<input type="text" name="twitterid" id="twitterid" class="input-text" value="<?php echo $_sellerInfomation['twitterid'] ?>" />
				</div>
			</div>
			<div class="field facebookid">
				<label class="label" for="facebookid"><span><?php /* @escapeNotVerified */ echo __('Facebook ID') ?></span></label>				
				<div class="control">
					<input type="text" name="facebookid" id="facebookid" class="input-text" value="<?php echo $_sellerInfomation['facebookid'] ?>" />
				</div>
			</div>
			<div class="field contactnumber">
				<label class="label" for="contactnumber"><span><?php /* @escapeNotVerified */ echo __('Contact Number') ?></span></label>
				<div class="control">
					<input type="text" name="contactnumber" id="contactnumber" class="input-text" value="<?php echo $_sellerInfomation['contactnumber'] ?>" />
				</div>
			</div>
			<div class="field storetitle">
				<label class="label" for="storetitle"><span><?php /* @escapeNotVerified */ echo __('Store Title') ?></span></label>
				<div class="control">
					<input type="text" name="storetitle" id="storetitle" class="input-text" value="<?php echo $_sellerInfomation['storetitle'] ?>" />
				</div>				
			</div>
			<div class="field storeurl">
				<label class="label" for="storeurl"><span><?php /* @escapeNotVerified */ echo __('Store Url') ?></span></label>
				<div class="control">
					<input type="text" name="storeurl" id="storeurl" class="input-text" value="<?php echo $_sellerInfomation['storeurl'] ?>" />
				</div>				
			</div>
			<div class="field bannerimg">
				<label for="bannerimg"><span><?php /* @escapeNotVerified */ echo __('Company Banner') ?></span></label>
				<div class="control">
					<input type="file" id="bannerimg" name="bannerimg" title="<?php /* @escapeNotVerified */ echo __('Banner Pic') ?>" class="input-text banner" size="26">					
					<?php if($_sellerInfomation['bannerimg']){ 
						$_urlImage=$block->getUrlImage($_sellerInfomation['bannerimg']);
					?>
					<div class="block block-image">
						<img src="<?php echo $_urlImage ?>" title="" alt="" />
						<input type="checkbox" id="bannerimg_delete" value="1" name="bannerimg[delete]" />
						<label for="bannerimg_delete"><?php /* @escapeNotVerified */ echo __('Delete Banner Image') ?></label>
						<input type="hidden" name="bannerimg[value]" value="<?php echo $_sellerInfomation['bannerimg'] ?>" />
					</div>
					<?php } ?>
				</div>
			</div>
			<div class="field logoimg">
				<label for="logoimg"><span><?php /* @escapeNotVerified */ echo __('Company Logo') ?></span></label>
				<div class="control">
					<input type="file" id="logoimg" name="logoimg" title="<?php /* @escapeNotVerified */ echo __('Logo Pic') ?>" class="input-text logoimg" size="26">					
					<?php if($_sellerInfomation['logoimg']){ 
						$_urlImage=$block->getUrlImage($_sellerInfomation['logoimg']);
					?>
					<div class="block block-image">
						<img src="<?php echo $_urlImage ?>" title="" alt="" />
						<input type="checkbox" value="1" id="logoimg_delete" name="logoimg[delete]" />
						<label for="logoimg_delete"><?php /* @escapeNotVerified */ echo __('Delete Logo Image') ?></label>
						<input type="hidden" name="logoimg[value]" value="<?php echo $_sellerInfomation['logoimg'] ?>" />
					</div>
					<?php } ?>					
				</div>
			</div>			
			<div class="field description">
				<label><span><?php /* @escapeNotVerified */ echo __('Company Description') ?></span></label>
				<div class="control">
					<textarea name='description' title='description' id='description' class='input-text compdesi wysiwyg-editor' ><?php echo $_sellerInfomation['description'] ?></textarea>
				</div>
			</div>			
			<div class="field returnpolicy">
				<label><span><?php /* @escapeNotVerified */ echo __('Return Policy') ?></span></label>
				<div class="control">
					<textarea name='returnpolicy' title='return policy' id='returnpolicy' class='input-text compdesi wysiwyg-editor' ><?php echo $_sellerInfomation['returnpolicy'] ?></textarea>
				</div>
			</div>			
			<div class="field shippingpolicy">
				<label><span><?php /* @escapeNotVerified */ echo __('Shipping Policy') ?></span></label>
				<div class="control">
					<textarea name='shippingpolicy' title='shipping policy' id='shippingpolicy' class='input-text compdesi wysiwyg-editor' ><?php echo $_sellerInfomation['shippingpolicy'] ?></textarea>
				</div>
			</div>
			<div class="field country">
				<label><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
				<div class="control">
					<select id="country" name="country">
						<option disabled="disabled" selected="selected" value=""><?php /* @escapeNotVerified */ echo __('Select Country') ?></option>
					<?php
						$_countries=$block->_getOptionsCountry();
						foreach($_countries as $k=>$_countryitem){						
						if(!$k) continue;
						if($_countryitem['value']==$_sellerInfomation['country']){
					?>						
						<option value="<?php echo $_countryitem['value']?>" selected="selected" ><?php echo $_countryitem['label']?></option>
						<?php }else{ ?>
						<option value="<?php echo $_countryitem['value']?>"><?php echo $_countryitem['label']?></option>
						<?php } ?>
					<?php } ?>
					</select>
				</div>
			</div>
			<div class="field metakeywords">
				<label><span><?php /* @escapeNotVerified */ echo __('Meta Keywords') ?></span></label>
				<div class="control">
					<textarea name="meta_keyword" id="meta_keyword" class="input-text compdesi"><?php echo $_sellerInfomation['meta_keyword'] ?></textarea>
				</div>
			</div>						
			<div class="field metadescription">
				<label><span><?php /* @escapeNotVerified */ echo __('Meta Description') ?></span></label>
				<div class="control">
					<textarea name="meta_description" id="meta_description" class="input-text compdesi"><?php echo $_sellerInfomation['meta_description'] ?></textarea>
				</div>
			</div>
			<div class="field block-button">
				<button type="submit" id="save-button" title="<?php /* @escapeNotVerified */ echo __('Save Profile') ?>">
					<span><span><?php /* @escapeNotVerified */ echo __('Save Profile') ?></span></span>
				</button>
			</div>
		</form>
	</div>
</div>
<script>
require([
	'jquery',
	'mage/adminhtml/wysiwyg/tiny_mce/setup'
], function(jQuery){

	var config = '',
		editor;

	jQuery.extend(config, {
		settings: {
			theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
				'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
			theme_advanced_buttons2: null,
			theme_advanced_buttons3: null,
			theme_advanced_buttons4: null,
			theme_advanced_statusbar_location: null
		},
		files_browser_window_url: false
	});

	editor = new tinyMceWysiwygSetup(
		'description',
		config
	);

	editor.turnOn();

	jQuery('#description')
	.addClass('wysiwyg-editor')
	.data(
		'wysiwygEditor',
		editor
	);
	editor = new tinyMceWysiwygSetup(
		'returnpolicy',
		config
	);
	editor.turnOn();
	jQuery('#returnpolicy')
	.addClass('wysiwyg-editor')
	.data(
		'wysiwygEditor',
		editor
	);

	editor = new tinyMceWysiwygSetup(
		'shippingpolicy',
		config
	);
	editor.turnOn();
	jQuery('#shippingpolicy')
	.addClass('wysiwyg-editor')
	.data(
		'wysiwygEditor',
		editor
	);
});
</script>